<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>answer_PTTEP-ALFRED</name>
   <tag></tag>
   <elementGuidId>00077621-fbea-44d4-a94a-e0c9893c62ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='wc-list']/descendant::p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='wc-list']/descendant::p</value>
   </webElementProperties>
</WebElementEntity>
